# Generated by Django 5.2 on 2025-04-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('n', 'In Progress'), ('d', 'done')], default='n', max_length=1),
        ),
    ]
